### ISSUE TITLE
[Bug] 메인 페이지에 이미지 띄우기

### ISSUE THREAD

**Issue by yeslee-v** [GwaChaePah/backend#21]
- admin에서 이미지를 추가하면, 처음에는 잘 보인다
- 하지만, sleep 시간 후 다시 접속하거나, 다시 deploy를 하면 보이지 않는다

<img width="461" alt="Screen Shot 2021-10-15 at 2 47 38 PM" src="https://user-images.githubusercontent.com/56112790/137439597-dddf0baf-87b3-44fc-80dd-91ef2133ded4.png">

**Comment by 3Cat-jaguar** [comment]
ㅠㅠㅠ

**Comment by stopminbeom** [comment]
ㅠㅍㅍㅍ왜 안올라가는걸까요

**Comment by yeslee-v** [comment]
@JongeunKeum 맞아요. 저도 그렇게 알고 있었는데, 어느 순간 다시 해봐야하나? 라는 생각이 들어서요.. 그럼 지금 하는거까지만 해보고 안되면, 바로 open API로 넘어갈게요!

**Comment by stopminbeom** [comment]
1. settings.py의 cloudinary.config 안의 내용을 대문자로 수정
2. heroku서버의 vars에 cloudinary 안의 값들 등록
3. cloudinary.config -> CLOUDINARY_STORAGE로 변경
