### ISSUE TITLE
농수산가격 api 요청 스케쥴 시간 조정

### ISSUE THREAD

**Issue by 3Cat-jaguar** [GwaChaePah/backend#44]
현재까지 데이터 들어온 것을 확인해보니 오후 3시에는 가격정보가 업로드가 안되는 것 같고,
오후 5시에는 다 들어오는 것 같습니다.
그래서 api 요청 스케쥴러를 오후 4시, 오후 5시, 오후 6시로 셋팅하면 어떨까 제안해봅니다.

**Comment by JongeunKeum** [comment]
<img width="1038" alt="스크린샷 2021-11-02 오후 10 00 45" src="https://user-images.githubusercontent.com/61774034/139851701-eddad014-b96d-404e-8c0a-8ee19d06c3a2.png">
open api를 받아오는 스케줄러를 2개로 줄이고, 오후 4시와 6시로 시간을 수정했다.
