### ISSUE TITLE
open api 불러온 데이터 중 옛날 데이터 삭제

### ISSUE THREAD

**Issue by JongeunKeum** [GwaChaePah/backend#45]
- 데이터를 계속 쌓아둘 필요는 없으니까, 일정 기간 이전 데이터는 지워야 한다.
- 일요일을 기준으로 2주치가 쌓였을 때, 이전 일주일치를 지우자(일요일까지, 지우고나면 월->일 최신순으로 데이터가 남아있게)
- 이 코드를 안 짰어요! 짜야혀!

**Comment by 3Cat-jaguar** [comment]
#44 api 받아와서 가격정보 데이터 추가하는 건은 오후 4시, 오후 6시 두 건으로 처리하고,
데이터 삭제하는 건을 매일 2주 전 데이터를 삭제할 수 있도록 스케쥴 하나 넣는 것으로 하면 좋을 것 같습니다.

**Comment by 3Cat-jaguar** [comment]
삭제하는 스케쥴 명령어는 수행하는 날짜에서 2주 전보다 오래된 데이터를 전부 불러와서 해당 쿼리셋에 있는 데이터 삭제하도록 합시다. 하루 스케쥴 안돌더라도 다음에 돌 때 실패한 부분까지 다 불러와서 삭제할 수 있도록
