### ISSUE TITLE
comment api 필터 동적 처리

### ISSUE THREAD

**Issue by 3Cat-jaguar** [GwaChaePah/backend#59]
현재는 comment-api 데이터를 post_key=8 인 경우로 필터하고있는데
url 에 들어오는 pk 값을 받아 그 값에 맞는 comment 데이터가 필터링되도록 처리하자

**Comment by yeslee-v** [comment]
8이라는 숫자를 직접 넣은 이유는 id를 어떻게 가져와야하는지에 대해 잘 모르겠어서 일단을 저렇게 넣었었어요.
