### ISSUE TITLE
post 와 board 의 혼선 줄이기

### ISSUE THREAD

**Issue by 3Cat-jaguar** [GwaChaePah/backend#60]
post table 에 있는 데이터를 모두 보내주는 api 이름이 post-api 로 되어있다.
그런데 보드 페이지에서 요청할 데이터/ 특정 포스트의 페이지에서 요청할 데이터 로 구분하면 어떨까?
- ylee 의 제안
1) board-api :  post table 데이터 중 board 페이지에서 보여질 데이터를 보내는 api
2) post-api/<int:pk> : 특정 pk 의 포스트를 post 페이지에서 보여지는데 필요한 데이터를 보내는 api
3) comment-api/<int:pk> : 특정 pk 의 포스트에 해당하는 댓글 데이터를 보내는 api

`2)` 와 `3)` 의 내용을 합쳐서 post-api/<int:pk> 로 api 요청이 들어왔을 때 해당 pk 의 post data 와 그에 종속된 comment data 를 같이 한번에 보내줄수는 없을까?

**Comment by 3Cat-jaguar** [comment]
지금 생각나는 방법은  search-api?search=keyword 처럼 post-api?id=pk 로 url 이 오는 경우에 id=pk 인 post와 그에 해당하는 comment 데이터를 필터링하면 되지 않을까?
이 방법을 쓰면 comment table 에서 post_key 를 예전 방식대로 PK 값을 숫자로 저장하는 경우에도 데이터 불러오는 것이 가능할텐데 숫자로 저장하는 것과 post object 자체를 저장하는 것 중 어느쪽이 더 좋은 방법인지는 모르겠다. 숫자만 저장하는게 용량을 덜 잡아먹을 것 같은 느낌이지만 그냥 느낌일뿐이라서.. 찾아봐야할듯

**Comment by yeslee-v** [comment]
안그래도 어제 그 부분 진행하면서 느낀건데, 네이밍할 때, 프론트와 통일성이 있었으면 지금 이 고민을 안해도 되겠다는 생각이 들었어요. 다만, 2+3 기능이 현재 comment-api에 해당됩니다. (이 부분은 #56 다시 한 번 확인해주세요.) 그리고, (나중에 user_key도 바꾸겠지만) post_key가 외래키로 바뀐 이유는, post table과 comment table이 종속 관계를 가지기 때문이에요. post_key의 field를 바꾸고 확인해보니, 숫자가 아닌 post object로 들어가게 된겁니다. 용량에 관해 언급하셨는데, 잘 모르다보니 이해가 잘 안가네요.

**Comment by 3Cat-jaguar** [comment]
#56 봤는데 지금은 comment-api 는 포스트는 안주고 코멘트 데이터만 가져와서 보내주더라구요
제가 2+3 을 얘기한거는 뭐시기-api/pk 하면 pk 에 해당하는 포스트데이터랑 코멘트 데이터를 같이 주면 어떨까 한거였어요
그러면 프론트가 한번만 요청해도 되니까
곧 만나니까 줌에서 얘기해봐용
