### ISSUE TITLE
board-api 요청시 뒤에 / 를 붙이면 에러발생하는 건

### ISSUE THREAD

**Issue by 3Cat-jaguar** [GwaChaePah/backend#84]
현재 board-api 를 요청하는 방법
1. `도메인/board-api` 로 요청
2. `도메인/board-api?search=검색어` 로 요청
3. `도메인/board-api?tag=태그번호` 로 요청
4. `도메인/board-api?search=검색어&tag=태그번호` 로 요청

board 전체 데이터를 받기위해서는 1 방법을 사용해야한다
그런데, `도메인/board-api` 를 입력했을때 자동으로 뒤에 `/`가 붙으면서 에러가 발생하는 케이스가 발생한다
`도메인/board-api/` 로 연결되는 path 가 없기때문인데 뒤에 `/` 를 붙여 검색하는 경우에 전체 케이스인 `도메인/board-api` 로 연결되어 해당 값이 보내지도록 처리해야할 것 같다

**Comment by deftones88** [comment]
tag로 불러오는 형식으로 해결했습니다. 감사합니다.
