### ISSUE TITLE
search-api 에서 정렬/분류가 안되는 문제

### ISSUE THREAD

**Issue by yeslee-v** [GwaChaePah/backend#85]
- 프론트 @deftones88 과 search 페이지 대화 중, 해당 검색어의 데이터를 보내는데, 시간 정렬과 rank 구분이 되어있지 않다.

![Screen Shot 2021-11-09 at 10 39 14](https://user-images.githubusercontent.com/56112790/140846224-fcf54396-433f-48c3-82ea-29d2373adf29.png)

**Comment by JongeunKeum** [comment]
근데 이거 id로 정렬하지 않았었나요..??

**Comment by yeslee-v** [comment]
근데 안되어있어서, 다시 한 번 확인해봐야할거같아요

**Comment by 3Cat-jaguar** [comment]
아 서치api 예전버전으로 돌리면서 복붙했던게 오더링부분이 빠져있는거였네요

**Comment by JongeunKeum** [comment]
헣 하나씩 놓치는 부분들이 있네요 🥲

**Comment by deftones88** [comment]
기다리고 있겠습니다
