### ISSUE TITLE
get 방식 외의 API 추가로 만들기

### ISSUE THREAD

**Issue by 3Cat-jaguar** [GwaChaePah/backend#91]
api를 다 만들었다고 생각했는데 우리가 만든건 read 만 되는 api 였네요...

우리 그동안 만든 api 외에는 views.py 에 있는 함수들 만들때 페이지에서 무슨 버튼 눌려서 어떤 도메인으로 가면 바로 실행되도록 테스트해봤는데(수정하기 버튼이 눌리면 edit path로 가면서 edit 함수 실행, 삭제하기 버튼 눌리면 delete path 로 이동하면서 delete 함수 실행, 함수 결과에 따라 어느 페이지로 이동),  생각해보니 이건 프론트의 방식이네요.

실제로 백이 받는건 사용자가 어떤 버튼을 눌렸을때 그에 대한 request 를 http 로 프론트가 보내줄테고, 이때 어디에서 어떤 요청이 있었는지, 어떤 작업을 필요로하는지를 post(C) get(R) put(U) delete(D) 라는 http method 로 보내주는걸 읽어서 작업하고 그에 대한 결과를 프론트에 http errorcode 나 json 으로 response 해주는 api 작업을 추가로 더 해야겠어요 

일단 오늘 user 부분 진행하시면서 회원가입시 post request 를 받을테니까 user 정상적으로 추가됐는지, 실패했는지(username이 이미 있다거나 등등의 이유로) 그 결과 보내주는 api랑,  로그인시 username 이랑 password가  들어오면 get request에 token 정보 보내주는 api 를 만들어보면 좋겠어요

**Comment by yeslee-v** [comment]
프론트 이슈에 `FRONT BACK 합칠 때 SWAGGER 논의 필요 #24` 도 참고해주세요
